---
galaxy_info:
  author: Brian R. Jackson
  description: A role to manage Certbot for obtaining SSL certificates.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: GenericLinux
      versions:
        - all

argument_specs:
  main:
    short_description: The main entry point for the certbot role.
    options:
      certbot_data_path:
        type: "str"
        required: true
        description: The base path for all Certbot data and configuration.
      gitea_domain:
        type: "str"
        required: true
        description: The domain to acquire a certificate for.
      dnsimple_oauth_token:
        type: "str"
        required: true
        description: The OAuth token for the DNSimple API.
      dnsimple_endpoint:
        type: "str"
        required: true
        description: The API endpoint for DNSimple.
