name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
    container:
      image: ghcr.io/jaxzin/jaxzin-infra-runner:latest
    steps:
      # Install node.js and npm
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/checkout@v4

      - name: Debug workspace and mount paths
        run: |
          echo "PWD: $(pwd)"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Listing contents of /github/workspace:"
          ls -la /github/workspace
          echo "Searching for jaxzin-infra-bootstrap:"
          find / -type d -name jaxzin-infra-bootstrap || echo "Not found"

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ansible-ci
          workspaceFolder: /github/workspace
          configFile: /github/workspace/.devcontainer/devcontainer.json
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all