name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
    container:
      image: ghcr.io/jaxzin/jaxzin-infra-runner@sha256:cff903315d73de05fd164d95d475ef7f04c36c90a4108247e4742eb339afc2b4
      privileged: true
      volumes:
        # Mount cgroups to allow Docker-in-Docker to work properly.
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      capabilities:
        - NET_ADMIN
        - NET_RAW
    steps:
      - name: Install and start Docker Daemon
        run: |
          apt-get update
          apt-get install -y docker.io
          update-alternatives --set iptables /usr/sbin/iptables-legacy
          update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
          dockerd --storage-driver=vfs --host=unix:///var/run/docker.sock &
          echo "Waiting for dockerd..."
          while ! docker info >/dev/null 2>&1; do sleep 1; done
        env:
          DOCKER_TLS_CERTDIR: ""

      - uses: actions/checkout@v4

      - name: Run Molecule Tests inside DevContainer
        uses: devcontainers/ci@v0.3
        env:
          GITHUB_REF_NAME: ${{ gitea.ref_name }}
        with:
          imageName: ghcr.io/jaxzin/jaxzin-infra-bootstrap
          imageTag: dev-${{ gitea.ref_name }}
          cacheFrom: ghcr.io/jaxzin/jaxzin-infra-bootstrap:dev-main
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all