name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
    container:
      image: ghcr.io/jaxzin/jaxzin-infra-runner@sha256:cff903315d73de05fd164d95d475ef7f04c36c90a4108247e4742eb339afc2b4
      privileged: true
      volumes:
        # Mount the Docker socket to allow the job container to communicate with the runner Docker service.
        - /var/run/docker.sock:/var/run/docker.sock
    services:
      docker:
        name: docker
        image: docker:dind
        options: --privileged --shm-size=2g
    steps:
#      - name: Install curl
#        run: |
#          which apk && apk add --no-cache curl || echo "apk not available"
#      # Install node.js and npm
#      - name: Install Node (Alpine-compatible)
#        run: |
#          NODE_VERSION=18.17.1
#          ARCH=x64
#          curl -fsSL https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-musl-$ARCH.tar.gz -o node.tar.gz
#          mkdir -p $HOME/.local/node
#          tar -xzf node.tar.gz -C $HOME/.local/node --strip-components=1
#          echo "$HOME/.local/node/bin" >> $GITHUB_PATH
#      # Install node.js and npm
#      - name: Install Node.js and npm
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18'
#
      - uses: actions/checkout@v4

      - name: Resolve DinD container IP
        id: get-dind-ip
        run: |
          ip=$(getent hosts docker | awk '{ print $1 }')
          echo "DOCKER_HOST=tcp://$ip:2375" >> $GITHUB_ENV
          echo "Resolved DOCKER_HOST=tcp://$ip:2375"

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ansible-ci
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all