name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
#    container:
#      image: ghcr.io/jaxzin/jaxzin-infra-runner:latest
    steps:
      - name: Install curl
        run: |
          which apk && apk add --no-cache curl || echo "apk not available"
      # Install node.js and npm
      - name: Install Node (Alpine-compatible)
        run: |
          NODE_VERSION=18.17.1
          ARCH=x64
          curl -fsSL https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-musl-$ARCH.tar.gz -o node.tar.gz
          mkdir -p $HOME/.local/node
          tar -xzf node.tar.gz -C $HOME/.local/node --strip-components=1
          echo "$HOME/.local/node/bin" >> $GITHUB_PATH
      # Install node.js and npm
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/checkout@v4

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ansible-ci
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all