name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
#    container:
#      image: ghcr.io/jaxzin/jaxzin-infra-runner:latest
    steps:
      - name: Ensure node is in PATH
        run: |
          export PATH="/usr/local/bin:$PATH"
          which node
          node -v
      - uses: actions/checkout@v4
      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ansible-ci
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all