name: Ansible Molecule CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: linux
    container:
      image: ghcr.io/jaxzin/jaxzin-infra-runner@sha256:cff903315d73de05fd164d95d475ef7f04c36c90a4108247e4742eb339afc2b4
      privileged: true
      volumes:
        # Mount cgroups to allow Docker-in-Docker to work properly.
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      capabilities:
        - NET_ADMIN
        - NET_RAW
    steps:
      - name: Install and start Docker Daemon
        run: |
          apt-get update
          apt-get install -y docker.io
          dockerd --host=unix:///var/run/docker.sock &
          echo "Waiting for dockerd..."
          while ! docker info >/dev/null 2>&1; do sleep 1; done
        env:
          DOCKER_TLS_CERTDIR: ""
#      - name: Install curl
#        run: |
#          which apk && apk add --no-cache curl || echo "apk not available"
#      # Install node.js and npm
#      - name: Install Node (Alpine-compatible)
#        run: |
#          NODE_VERSION=18.17.1
#          ARCH=x64
#          curl -fsSL https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-musl-$ARCH.tar.gz -o node.tar.gz
#          mkdir -p $HOME/.local/node
#          tar -xzf node.tar.gz -C $HOME/.local/node --strip-components=1
#          echo "$HOME/.local/node/bin" >> $GITHUB_PATH
#      # Install node.js and npm
#      - name: Install Node.js and npm
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18'
#
      - uses: actions/checkout@v4

#      - name: Resolve DinD container IP
#        id: get-dind-ip
#        run: |
#          ip=$(getent hosts docker | awk '{ print $1 }')
#          echo "DOCKER_HOST=tcp://$ip:2375" >> $GITHUB_ENV
#          echo "Resolved DOCKER_HOST=tcp://$ip:2375"
      - name: Pause to debug
        run: sleep 3600

      - name: Build Devcontainer Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ansible-ci
          runCmd: |
            set -e
            echo "Container built successfully. Running tests..."
            cd /workspaces/jaxzin-infra-bootstrap/
            make molecule -- test --all