blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/jaxzin/jaxzin-infra-bootstrap/discussions/new?category=q-a
    about: Please ask and answer questions here.
