---
- name: Tier 2 | Ensure Hyper Backup package is installed
  include_role:
    name: tafeen.synology.syno_pkg_install
  vars:
    syno_pkg_name: HyperBackup
    syno_pkg_state: present


# I know this is fragile, but its only purpose to ensure backups are configured for the Gitea volume
# If repo_4 and task_4 are not present, then we're recovering from a disaster and we need to reconfigure Hyper Backup

- name: Tier 2 | Configure Hyper Backup B2 Repository (repo_4)
  community.general.ini_file:
    path: /var/packages/HyperBackup/etc/synobackup.conf
    section: repo_4
    option: "{{ item.option }}"
    value: "\"{{ item.value }}\""
    mode: "0644"
    owner: root
    group: root
    no_extra_spaces: yes
  loop:
    - { option: 'remote_bucket', value: '{{ hyperbackup_b2_remote_bucket }}' }
    - { option: 'remote_key', value: '{{ hyperbackup_b2_remote_key }}' }
    - { option: 'remote_secret', value: '{{ hyperbackup_b2_remote_secret }}' }
    - { option: 'remote_url', value: 's3.us-west-000.backblazeb2.com' }
    - { option: 'signature_version', value: 'v4' }
    - { option: 'target_type', value: 'cloud_image' }
    - { option: 'trans_type', value: 'aws_s3' }
    - { option: 'client_cache', value: '/volume1/@img_bkp_cache/ClientCache_cloud_image_aws_s3.U7MRcM' }
    - { option: 'cloud_cache', value: '/volume1/@img_bkp_cache/aws_s3_{{ hyperbackup_b2_remote_bucket }}_00044f3f5faca3f0000000004.GHGTdt' }
    - { option: 'name', value: '' }

  no_log: true # Hide the secret from logs
  notify:
    - Restart HyperBackup

- name: Tier 2 | Read synobackup.conf from target host
  ansible.builtin.slurp:
    src: /var/packages/HyperBackup/etc/synobackup.conf
  register: synobackup_conf_raw

- name: Tier 2 | Parse synobackup.conf and update backup_folders
  ansible.builtin.set_fact:
    backup_folders: >-
      {{
        (synobackup_conf_raw.content | b64decode | community.general.from_ini)
        .get('task_4', {})
        .get('backup_folders', '[]') | from_json | default([]) | union(['/docker']) | sort | to_json
      }}

- debug:
    msg: "Backup folders for task_4: {{ backup_folders }}"

- name: Tier 2 | Configure Hyper Backup B2 Task Folders (task_4)
  community.general.ini_file:
    path: /var/packages/HyperBackup/etc/synobackup.conf
    section: task_4
    option: backup_folders
    value: "{{ backup_folders | replace('\", \"', '\",\"') }}"
    mode: "0644"
    owner: root
    group: root
    no_extra_spaces: yes
  notify:
    - Restart HyperBackup
