---
galaxy_info:
  author: Brian R. Jackson
  description: A role to configure automated backups of Gitea to a Backblaze B2 bucket.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: GenericLinux
      versions:
        - all

argument_specs:
  main:
    short_description: The main entry point for the gitea_backup role.
    options:
      b2_bucket_name:
        type: "str"
        required: true
        description: The name of the Backblaze B2 bucket to upload backups to.
      b2_application_key_id:
        type: "str"
        required: true
        description: The ID of the Backblaze B2 application key.
      b2_application_key:
        type: "str"
        required: true
        description: The Backblaze B2 application key secret.
        no_log: true