name: "Prebuild DevContainer"

on:
  push:
    branches:
      - '**'        # all branches, including feature/*
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-prepush:
    runs-on: ubuntu-latest
    outputs:
      image_ref: ${{ steps.img.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build devcontainer image
        id: img
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:main
          push: always
          platform: linux/amd64,linux/arm64