name: Mirror Health Check

on:
  schedule:
    - cron: '0 0 * * *'  # daily

jobs:
  check-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fail if mirror stale (>24 h)
        run: |
          last=$(git show -s --format=%ct HEAD)
          now=$(date +%s)
          delta=$(( (now - last) / 3600 ))
          if [ $delta -gt 24 ]; then
            echo "Mirror stale: $delta hours since last commit"
            exit 1
          else
            echo "Mirror healthy: $delta hours since last commit"
          fi

      - name: Notify Discord on failure
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ":rotating_light: Mirror has not updated in over 24 hours!"
