# .github/workflows/secret-scan.yml
name: Secret Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for a full scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          # Gitleaks uses the GITHUB_TOKEN to report findings back to the GitHub Security tab
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
